# language target
language: cpp
compiler: gcc

# main build matrix
matrix:
  include:
    - name: "Bionic Ubuntu Linux"
      os: linux
      dist: bionic
      sudo: required
      env: TARGETOS=bionic-linux

# install, install QT5.12.3 from ppa
install:
  - echo "deb http://archive.neon.kde.org/user/ bionic main" > /etc/apt/sources.list.d/kde_neon.list
  - echo "deb-src http://archive.neon.kde.org/user/ bionic main" > /etc/apt/sources.list.d/kde_neon.list
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade -o dpkg::options::="--force-overwrite"
  - sudo apt install build-essential g++ make ffmpeg sox mplayer libnotify-dev mesa-common-dev libglvnd-dev desktop-file-utils
  - qtchooser -print-env
  - qmake -v
  - sudo apt install qt5-default qtdeclarative5-dev qtmultimedia5-dev qt5-qmake

# build & test scripts
script:
  - qmake mystiq.pro
  - make
  - sudo make install

# notifications (only via telegram)
notifications:
  email: true
  #webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# make the AppImage bundle
before_deploy:
    # install AppImage toolchain
  - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod +x *.AppImage
  - chmod +x comple*.sh
  # build the AppDir
  - make install INSTALL_ROOT=AppDir
  # add extra tools
  - ./complete_appdir.sh
  # run the linuxdeploy script
  - ./linuxdeploy-x86_64.AppImage --appdir=AppDir --plugin qt --output appimage
  # listing the result
  - ls -lh *.AppImage
  # get the tag version
  - export VERSION="$(git describe --tags --exact-match HEAD 2> /dev/null)"
  # set the version on the filename
  - mv MystiQ*AppImage MystiQ_$VERSION.AppImage

# deploy to Github
deploy:
  # deploy on linux
  - provider: releases
    api_key: $OAUTHTOKEN
    file_glob: true
    draft: true
    overwrite: true
    skip_cleanup: true
    on:
      repo: llamaret/MystiQ
      tags: true
    file: 
      - ./MystiQ*.AppImage

