# language target
language: cpp
compiler: gcc

# main build matrix
matrix:
  include:
    - name: "Bionic Ubuntu Linux"
      os: linux
      dist: bionic
      sudo: required
      env: TARGETOS=bionic-linux

# install, install QT5.12.3 from ppa
install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-bionic
  - sudo apt update
  - sudo apt install build-essential g++ make ffmpeg sox mplayer libnotify-dev mesa-common-dev libglvnd-dev
  - sudo apt install qt-latest tree
  - echo "/opt/qt512/bin" | sudo tee /etc/xdg/qtchooser/default.conf
  - echo "/opt/qt512/lib" | sudo tee -a /etc/xdg/qtchooser/default.conf
  - qtchooser -print-env
  - qmake -v

# build & test scripts
script:
  - qmake mystiq.pro
  - make
  - sudo make install

# notifications (only via telegram)
notifications:
  email: true
  #webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

# make the AppImage bundle
before_deploy:
    # install AppImage toolchain
  - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod +x *.AppImage
  # build the AppDir
  - make install INSTALL_ROOT=AppDir
  # add extra tools
  - ./complete_appdir.sh
  # run the linuxdeploy script
  - ./linuxdeploy-x86_64.AppImage --appdir=AppDir --plugin qt --output appimage
  # listing the result
  - ls -lh *.AppImage
  # get the tag version
  export VERSION="$(git describe --tags --exact-match HEAD 2> /dev/null)"
  # set the version on the filename
  - mv MystiQ*AppImage MystiQ_$VERSION.AppImage

# deploy to Github
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  draft: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
  file:
    - ./*.AppImage
  on:
    all_branches: true  
