name: Packages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Updating OS
      run: sudo apt update && sudo apt full-upgrade
    - name: Install Qt5Gui
      run: sudo apt install ffmpeg sox mplayer libnotify-dev qt5-default qt5-qmake g++ make
    - name: Qt5 Version info
      run: dpkg -l | grep qt5-default    
    - name: PPA Kubuntu
      run: sudo add-apt-repository ppa:kubuntu-ppa/backport && sudo apt update && upgrade && sudo apt-get install plasma-desktop
    - name: qmake
      run: qmake mystiq.pro
    - name: make
      run: make
    - name: strip
      run: strip mystiq 
    - name: installing
      run: sudo make install
