name: QT5/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v1.0.0
    - name: Checkout
      uses: actions/checkout@v1
    - name: install qt
      uses: actions/install-qt-action@v0.1.1
      with:
        packages: 'qt.qt5.5124.gcc_64, qt.qt5.5124.android_arm64_v8a'
    - uses: actions/checkout@v1
    - name: qmake
      run: qmake mystiq.pro
    - name: make
      run: make
