name: QT5/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v1.0.0
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Qt5Gui
      run: sudo apt install ffmpeg sox mplayer libnotify-dev qt5-default qt5-qmake g++ make  
    - name: qmake
      run: qmake mystiq.pro
    - name: make
      run: make
    - name: strip
      run: strip mystiq  
    - name: Create a Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.1
    - name: Checkout code
      uses: actions/checkout@master
    - name: Build project # This would actually build your project, using zip for an example artifact
      run: |
          zip --junk-paths my-artifact README.md
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./mystiq-ubuntu.zip
          asset_name: mystiq-ubuntu.zip
          asset_content_type: application/zip
