name: QT5/C++ CI

on: [push] 
jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v1.0.0
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Qt5Gui
      run: sudo apt install ffmpeg sox mplayer libnotify-dev qt5-default qt5-qmake g++ make  
    - name: qmake
      run: qmake mystiq.pro
    - name: make
      run: make
    - name: strip
      run: strip mystiq 
    - name: cat Makefile
      run: cat ./Makefile
    - name: Make Clean
      run: make clean 

